#pragma once
#include <Windows.h>
#include <cstdint>
#include <string>
#include <string_view>
#include "..\_Script_CoreUObject\Object.hpp"
namespace _Script_Engine {
struct ActorComponent;
}
namespace _Script_CoreUObject {
struct Class;
}
namespace _Script_Engine {
#pragma pack(push, 1)
struct SCS_Node : public _Script_CoreUObject::Object {
    void* get_ComponentClass();
    _Script_Engine::ActorComponent*& get_ComponentTemplate();
    void* get_CookedComponentInstancingData();
    void* get_VariableName();
    void* get_AttachToName();
    void* get_ParentComponentOrVariableName();
    void* get_ParentComponentOwnerClassName();
    bool get_bIsParentComponentNative();
    void set_bIsParentComponentNative(bool value);
    void* get_ChildNodes();
    void* get_MetaDataArray();
    void* get_VariableGuid();
    bool get_bIsFalseRoot();
    void set_bIsFalseRoot(bool value);
    bool get_bIsNative();
    void set_bIsNative(bool value);
    void* get_NativeComponentName();
    bool get_bVariableNameAutoGenerated();
    void set_bVariableNameAutoGenerated(bool value);
    void* get_InternalVariableName();
    static _Script_CoreUObject::Class* static_class();
}; // Size: 0x28
#pragma pack(pop)
}
