#include "..\FUObjectArray.hpp"
#include "..\_Script_CoreUObject\Class.hpp"
#include "..\_Script_CoreUObject\Object.hpp"
#include "ActorComponent.hpp"
#include "SCS_Node.hpp"
void* _Script_Engine::SCS_Node::get_ComponentClass() {
    return (void*)((uintptr_t)this + 0x28);
}
_Script_Engine::ActorComponent*& _Script_Engine::SCS_Node::get_ComponentTemplate() {
    return *(_Script_Engine::ActorComponent**)((uintptr_t)this + 0x30);
}
bool _Script_Engine::SCS_Node::get_bIsParentComponentNative() {
    return (*(uint8_t*)((uintptr_t)this + 0xa8 + 0)) & 1 != 0;
}
void* _Script_Engine::SCS_Node::get_VariableName() {
    return (void*)((uintptr_t)this + 0x88);
}
void* _Script_Engine::SCS_Node::get_CookedComponentInstancingData() {
    return (void*)((uintptr_t)this + 0x38);
}
void* _Script_Engine::SCS_Node::get_ParentComponentOwnerClassName() {
    return (void*)((uintptr_t)this + 0xa0);
}
void* _Script_Engine::SCS_Node::get_AttachToName() {
    return (void*)((uintptr_t)this + 0x90);
}
void* _Script_Engine::SCS_Node::get_ParentComponentOrVariableName() {
    return (void*)((uintptr_t)this + 0x98);
}
void _Script_Engine::SCS_Node::set_bIsParentComponentNative(bool value) {
    const auto cur_value = *(uint8_t*)((uintptr_t)this + 0xa8 + 0);
    *(uint8_t*)((uintptr_t)this + 0xa8 + 0) = (cur_value & ~1) | (value ? 1 : 0);
}
void* _Script_Engine::SCS_Node::get_ChildNodes() {
    return (void*)((uintptr_t)this + 0xb0);
}
void* _Script_Engine::SCS_Node::get_MetaDataArray() {
    return (void*)((uintptr_t)this + 0xc0);
}
void* _Script_Engine::SCS_Node::get_VariableGuid() {
    return (void*)((uintptr_t)this + 0xd0);
}
bool _Script_Engine::SCS_Node::get_bIsFalseRoot() {
    return (*(uint8_t*)((uintptr_t)this + 0xe0 + 0)) & 1 != 0;
}
void _Script_Engine::SCS_Node::set_bIsFalseRoot(bool value) {
    const auto cur_value = *(uint8_t*)((uintptr_t)this + 0xe0 + 0);
    *(uint8_t*)((uintptr_t)this + 0xe0 + 0) = (cur_value & ~1) | (value ? 1 : 0);
}
bool _Script_Engine::SCS_Node::get_bIsNative() {
    return (*(uint8_t*)((uintptr_t)this + 0xe1 + 0)) & 1 != 0;
}
void _Script_Engine::SCS_Node::set_bIsNative(bool value) {
    const auto cur_value = *(uint8_t*)((uintptr_t)this + 0xe1 + 0);
    *(uint8_t*)((uintptr_t)this + 0xe1 + 0) = (cur_value & ~1) | (value ? 1 : 0);
}
void* _Script_Engine::SCS_Node::get_NativeComponentName() {
    return (void*)((uintptr_t)this + 0xe8);
}
bool _Script_Engine::SCS_Node::get_bVariableNameAutoGenerated() {
    return (*(uint8_t*)((uintptr_t)this + 0xf0 + 0)) & 1 != 0;
}
void _Script_Engine::SCS_Node::set_bVariableNameAutoGenerated(bool value) {
    const auto cur_value = *(uint8_t*)((uintptr_t)this + 0xf0 + 0);
    *(uint8_t*)((uintptr_t)this + 0xf0 + 0) = (cur_value & ~1) | (value ? 1 : 0);
}
void* _Script_Engine::SCS_Node::get_InternalVariableName() {
    return (void*)((uintptr_t)this + 0xf8);
}
_Script_CoreUObject::Class* _Script_Engine::SCS_Node::static_class() {
    static auto result = (_Script_CoreUObject::Class*)FUObjectArray::get()->find_uobject(L"Class /Script/Engine.SCS_Node");
    return result;
}
